spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andiksetyawan/microservice-springboot.git
          searchPaths: 'configs/{application}'
        bootstrap: true
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

